----------------- CREATE TABLES --------------------------------------------

-- 2016 
CREATE TABLE public."2016_jury_results" (
	"Contestant" varchar(50) NULL,
	"Total score" int4 NULL,
	"Jury score" int4 NULL,
	"Televoting score" int4 NULL,
	"Austria" int4 NULL,
	"Iceland" int4 NULL,
	"Azerbaijan" int4 NULL,
	"San Marino" int4 NULL,
	"Czech Republic" int4 NULL,
	"Ireland" int4 NULL,
	"Georgia" int4 NULL,
	"Bosnia and Herzegovina" int4 NULL,
	"Malta" int4 NULL,
	"Spain" int4 NULL,
	"Finland" int4 NULL,
	"Switzerland" int4 NULL,
	"Denmark" int4 NULL,
	"France" int4 NULL,
	"Moldova" int4 NULL,
	"Armenia" int4 NULL,
	"Cyprus" int4 NULL,
	"Bulgaria" int4 NULL,
	"Netherlands" int4 NULL,
	"Latvia" int4 NULL,
	"Israel" int4 NULL,
	"Belarus" int4 NULL,
	"Germany" int4 NULL,
	"Russia" int4 NULL,
	"Norway" int4 NULL,
	"Australia" int4 NULL,
	"Belgium" int4 NULL,
	"United Kingdom" int4 NULL,
	"Croatia" int4 NULL,
	"Greece" int4 NULL,
	"Lithuania" int4 NULL,
	"Serbia" int4 NULL,
	"Macedonia" int4 NULL,
	"Albania" int4 NULL,
	"Estonia" int4 NULL,
	"Ukraine" int4 NULL,
	"Italy" int4 NULL,
	"Poland" int4 NULL,
	"Slovenia" int4 NULL,
	"Hungary" int4 NULL,
	"Montenegro" int4 NULL,
	"Sweden" int4 NULL,
	"year" int4 NULL
);



CREATE TABLE public."2016_televote_results" (
	"Contestant" varchar(50) NULL,
	"Total score" int4 NULL,
	"Jury score" int4 NULL,
	"Televoting score" int4 NULL,
	"Austria" int4 NULL,
	"Iceland" int4 NULL,
	"Azerbaijan" int4 NULL,
	"San Marino" int4 NULL,
	"Czech Republic" int4 NULL,
	"Ireland" int4 NULL,
	"Georgia" int4 NULL,
	"Bosnia and Herzegovina" int4 NULL,
	"Malta" int4 NULL,
	"Spain" int4 NULL,
	"Finland" int4 NULL,
	"Switzerland" int4 NULL,
	"Denmark" int4 NULL,
	"France" int4 NULL,
	"Moldova" int4 NULL,
	"Armenia" int4 NULL,
	"Cyprus" int4 NULL,
	"Bulgaria" int4 NULL,
	"Netherlands" int4 NULL,
	"Latvia" int4 NULL,
	"Israel" int4 NULL,
	"Belarus" int4 NULL,
	"Germany" int4 NULL,
	"Russia" int4 NULL,
	"Norway" int4 NULL,
	"Australia" int4 NULL,
	"Belgium" int4 NULL,
	"United Kingdom" int4 NULL,
	"Croatia" int4 NULL,
	"Greece" int4 NULL,
	"Lithuania" int4 NULL,
	"Serbia" int4 NULL,
	"Macedonia" int4 NULL,
	"Albania" int4 NULL,
	"Estonia" int4 NULL,
	"Ukraine" int4 NULL,
	"Italy" int4 NULL,
	"Poland" int4 NULL,
	"Slovenia" int4 NULL,
	"Hungary" int4 NULL,
	"Montenegro" int4 NULL,
	"Sweden" int4 NULL,
	"year" int4 NULL
);

CREATE TABLE public."2016_poll_results" (
	"Contestant" varchar(50) NULL,
	my_eurovision_scoreboard_points int4 NULL,
	eurovision_world_points int4 NULL,
	eurojury_jury_points int4 NULL,
	eurojury_online_points int4 NULL,
	discord_points int4 NULL,
	wiwiblogs_points int4 NULL,
	ogae_points int4 NULL,
	"year" int4 NULL
);


-- 2017
CREATE TABLE public."2017_jury_results" (
	"Contestant" varchar(50) NULL,
	"Total score" int4 NULL,
	"Jury score" int4 NULL,
	"Televoting score" int4 NULL,
	"Austria" int4 NULL,
	"Iceland" int4 NULL,
	"Azerbaijan" int4 NULL,
	"San Marino" int4 NULL,
	"Czech Republic" int4 NULL,
	"Ireland" int4 NULL,
	"Georgia" int4 NULL,
	"Bosnia and Herzegovina" int4 NULL,
	"Malta" int4 NULL,
	"Spain" int4 NULL,
	"Finland" int4 NULL,
	"Switzerland" int4 NULL,
	"Denmark" int4 NULL,
	"France" int4 NULL,
	"Moldova" int4 NULL,
	"Armenia" int4 NULL,
	"Cyprus" int4 NULL,
	"Bulgaria" int4 NULL,
	"Netherlands" int4 NULL,
	"Latvia" int4 NULL,
	"Israel" int4 NULL,
	"Belarus" int4 NULL,
	"Germany" int4 NULL,
	"Russia" int4 NULL,
	"Norway" int4 NULL,
	"Australia" int4 NULL,
	"Belgium" int4 NULL,
	"United Kingdom" int4 NULL,
	"Croatia" int4 NULL,
	"Greece" int4 NULL,
	"Lithuania" int4 NULL,
	"Serbia" int4 NULL,
	"Macedonia" int4 NULL,
	"Albania" int4 NULL,
	"Estonia" int4 NULL,
	"Ukraine" int4 NULL,
	"Italy" int4 NULL,
	"Poland" int4 NULL,
	"Slovenia" int4 NULL,
	"Hungary" int4 NULL,
	"Montenegro" int4 NULL,
	"Sweden" int4 NULL,
	"year" int4 NULL
);


CREATE TABLE public."2017_poll_results" (
	"Contestant" varchar(50) NULL,
	my_eurovision_scoreboard_points int4 NULL,
	eurovision_world_points int4 NULL,
	eurojury_jury_points int4 NULL,
	eurojury_online_points int4 NULL,
	discord_points int4 NULL,
	wiwiblogs_points int4 NULL,
	ogae_points int4 NULL,
	"year" int4 NULL
);



CREATE TABLE public."2017_televote_results" (
	"Contestant" varchar(50) NULL,
	"Total score" int4 NULL,
	"Jury score" int4 NULL,
	"Televoting score" int4 NULL,
	"Austria" int4 NULL,
	"Iceland" int4 NULL,
	"Azerbaijan" int4 NULL,
	"San Marino" int4 NULL,
	"Czech Republic" int4 NULL,
	"Ireland" int4 NULL,
	"Georgia" int4 NULL,
	"Bosnia and Herzegovina" int4 NULL,
	"Malta" int4 NULL,
	"Spain" int4 NULL,
	"Finland" int4 NULL,
	"Switzerland" int4 NULL,
	"Denmark" int4 NULL,
	"France" int4 NULL,
	"Moldova" int4 NULL,
	"Armenia" int4 NULL,
	"Cyprus" int4 NULL,
	"Bulgaria" int4 NULL,
	"Netherlands" int4 NULL,
	"Latvia" int4 NULL,
	"Israel" int4 NULL,
	"Belarus" int4 NULL,
	"Germany" int4 NULL,
	"Russia" int4 NULL,
	"Norway" int4 NULL,
	"Australia" int4 NULL,
	"Belgium" int4 NULL,
	"United Kingdom" int4 NULL,
	"Croatia" int4 NULL,
	"Greece" int4 NULL,
	"Lithuania" int4 NULL,
	"Serbia" int4 NULL,
	"Macedonia" int4 NULL,
	"Albania" int4 NULL,
	"Estonia" int4 NULL,
	"Ukraine" int4 NULL,
	"Italy" int4 NULL,
	"Poland" int4 NULL,
	"Slovenia" int4 NULL,
	"Hungary" int4 NULL,
	"Montenegro" int4 NULL,
	"Sweden" int4 NULL,
	"year" int4 NULL
);



-- 2018
CREATE TABLE public."2018_jury_results" (
	"Contestant" varchar(50) NULL,
	"Total score" int4 NULL,
	"Jury score" int4 NULL,
	"Televoting score" int4 NULL,
	"Austria" int4 NULL,
	"Iceland" int4 NULL,
	"Azerbaijan" int4 NULL,
	"San Marino" int4 NULL,
	"Czech Republic" int4 NULL,
	"Ireland" int4 NULL,
	"Georgia" int4 NULL,
	"Bosnia and Herzegovina" int4 NULL,
	"Malta" int4 NULL,
	"Spain" int4 NULL,
	"Finland" int4 NULL,
	"Switzerland" int4 NULL,
	"Denmark" int4 NULL,
	"France" int4 NULL,
	"Moldova" int4 NULL,
	"Armenia" int4 NULL,
	"Cyprus" int4 NULL,
	"Bulgaria" int4 NULL,
	"Netherlands" int4 NULL,
	"Latvia" int4 NULL,
	"Israel" int4 NULL,
	"Belarus" int4 NULL,
	"Germany" int4 NULL,
	"Russia" int4 NULL,
	"Norway" int4 NULL,
	"Australia" int4 NULL,
	"Belgium" int4 NULL,
	"United Kingdom" int4 NULL,
	"Croatia" int4 NULL,
	"Greece" int4 NULL,
	"Lithuania" int4 NULL,
	"Serbia" int4 NULL,
	"Macedonia" int4 NULL,
	"Albania" int4 NULL,
	"Estonia" int4 NULL,
	"Ukraine" int4 NULL,
	"Italy" int4 NULL,
	"Poland" int4 NULL,
	"Slovenia" int4 NULL,
	"Hungary" int4 NULL,
	"Montenegro" int4 NULL,
	"Sweden" int4 NULL,
	"year" int4 NULL
);


CREATE TABLE public."2018_poll_results" (
	"Contestant" varchar(50) NULL,
	my_eurovision_scoreboard_points int4 NULL,
	eurovision_world_points int4 NULL,
	eurojury_jury_points int4 NULL,
	eurojury_online_points int4 NULL,
	discord_points int4 NULL,
	wiwiblogs_points int4 NULL,
	ogae_points int4 NULL,
	"year" int4 NULL
);



CREATE TABLE public."2018_televote_results" (
	"Contestant" varchar(50) NULL,
	"Total score" int4 NULL,
	"Jury score" int4 NULL,
	"Televoting score" int4 NULL,
	"Austria" int4 NULL,
	"Iceland" int4 NULL,
	"Azerbaijan" int4 NULL,
	"San Marino" int4 NULL,
	"Czech Republic" int4 NULL,
	"Ireland" int4 NULL,
	"Georgia" int4 NULL,
	"Bosnia and Herzegovina" int4 NULL,
	"Malta" int4 NULL,
	"Spain" int4 NULL,
	"Finland" int4 NULL,
	"Switzerland" int4 NULL,
	"Denmark" int4 NULL,
	"France" int4 NULL,
	"Moldova" int4 NULL,
	"Armenia" int4 NULL,
	"Cyprus" int4 NULL,
	"Bulgaria" int4 NULL,
	"Netherlands" int4 NULL,
	"Latvia" int4 NULL,
	"Israel" int4 NULL,
	"Belarus" int4 NULL,
	"Germany" int4 NULL,
	"Russia" int4 NULL,
	"Norway" int4 NULL,
	"Australia" int4 NULL,
	"Belgium" int4 NULL,
	"United Kingdom" int4 NULL,
	"Croatia" int4 NULL,
	"Greece" int4 NULL,
	"Lithuania" int4 NULL,
	"Serbia" int4 NULL,
	"Macedonia" int4 NULL,
	"Albania" int4 NULL,
	"Estonia" int4 NULL,
	"Ukraine" int4 NULL,
	"Italy" int4 NULL,
	"Poland" int4 NULL,
	"Slovenia" int4 NULL,
	"Hungary" int4 NULL,
	"Montenegro" int4 NULL,
	"Sweden" int4 NULL,
	"year" int4 NULL
);

-- 2019
CREATE TABLE public."2019_jury_results" (
	"Contestant" varchar(50) NULL,
	"Total score" int4 NULL,
	"Jury score" int4 NULL,
	"Televoting score" int4 NULL,
	"Austria" int4 NULL,
	"Iceland" int4 NULL,
	"Azerbaijan" int4 NULL,
	"San Marino" int4 NULL,
	"Czech Republic" int4 NULL,
	"Ireland" int4 NULL,
	"Georgia" int4 NULL,
	"Bosnia and Herzegovina" int4 NULL,
	"Malta" int4 NULL,
	"Spain" int4 NULL,
	"Finland" int4 NULL,
	"Switzerland" int4 NULL,
	"Denmark" int4 NULL,
	"France" int4 NULL,
	"Moldova" int4 NULL,
	"Armenia" int4 NULL,
	"Cyprus" int4 NULL,
	"Bulgaria" int4 NULL,
	"Netherlands" int4 NULL,
	"Latvia" int4 NULL,
	"Israel" int4 NULL,
	"Belarus" int4 NULL,
	"Germany" int4 NULL,
	"Russia" int4 NULL,
	"Norway" int4 NULL,
	"Australia" int4 NULL,
	"Belgium" int4 NULL,
	"United Kingdom" int4 NULL,
	"Croatia" int4 NULL,
	"Greece" int4 NULL,
	"Lithuania" int4 NULL,
	"Serbia" int4 NULL,
	"Macedonia" int4 NULL,
	"Albania" int4 NULL,
	"Estonia" int4 NULL,
	"Ukraine" int4 NULL,
	"Italy" int4 NULL,
	"Poland" int4 NULL,
	"Slovenia" int4 NULL,
	"Hungary" int4 NULL,
	"Montenegro" int4 NULL,
	"Sweden" int4 NULL,
	"year" int4 NULL
);


CREATE TABLE public."2019_poll_results" (
	"Contestant" varchar(50) NULL,
	my_eurovision_scoreboard_points int4 NULL,
	eurovision_world_points int4 NULL,
	eurojury_jury_points int4 NULL,
	eurojury_online_points int4 NULL,
	discord_points int4 NULL,
	wiwiblogs_points int4 NULL,
	ogae_points int4 NULL,
	"year" int4 NULL
);



CREATE TABLE public."2019_televote_results" (
	"Contestant" varchar(50) NULL,
	"Total score" int4 NULL,
	"Jury score" int4 NULL,
	"Televoting score" int4 NULL,
	"Austria" int4 NULL,
	"Iceland" int4 NULL,
	"Azerbaijan" int4 NULL,
	"San Marino" int4 NULL,
	"Czech Republic" int4 NULL,
	"Ireland" int4 NULL,
	"Georgia" int4 NULL,
	"Bosnia and Herzegovina" int4 NULL,
	"Malta" int4 NULL,
	"Spain" int4 NULL,
	"Finland" int4 NULL,
	"Switzerland" int4 NULL,
	"Denmark" int4 NULL,
	"France" int4 NULL,
	"Moldova" int4 NULL,
	"Armenia" int4 NULL,
	"Cyprus" int4 NULL,
	"Bulgaria" int4 NULL,
	"Netherlands" int4 NULL,
	"Latvia" int4 NULL,
	"Israel" int4 NULL,
	"Belarus" int4 NULL,
	"Germany" int4 NULL,
	"Russia" int4 NULL,
	"Norway" int4 NULL,
	"Australia" int4 NULL,
	"Belgium" int4 NULL,
	"United Kingdom" int4 NULL,
	"Croatia" int4 NULL,
	"Greece" int4 NULL,
	"Lithuania" int4 NULL,
	"Serbia" int4 NULL,
	"Macedonia" int4 NULL,
	"Albania" int4 NULL,
	"Estonia" int4 NULL,
	"Ukraine" int4 NULL,
	"Italy" int4 NULL,
	"Poland" int4 NULL,
	"Slovenia" int4 NULL,
	"Hungary" int4 NULL,
	"Montenegro" int4 NULL,
	"Sweden" int4 NULL,
	"year" int4 NULL
);


-- 2021
CREATE TABLE public."2021_jury_results" (
	"Contestant" varchar(50) NULL,
	"Total score" int4 NULL,
	"Jury score" int4 NULL,
	"Televoting score" int4 NULL,
	"Austria" int4 NULL,
	"Iceland" int4 NULL,
	"Azerbaijan" int4 NULL,
	"San Marino" int4 NULL,
	"Czech Republic" int4 NULL,
	"Ireland" int4 NULL,
	"Georgia" int4 NULL,
	"Bosnia and Herzegovina" int4 NULL,
	"Malta" int4 NULL,
	"Spain" int4 NULL,
	"Finland" int4 NULL,
	"Switzerland" int4 NULL,
	"Denmark" int4 NULL,
	"France" int4 NULL,
	"Moldova" int4 NULL,
	"Armenia" int4 NULL,
	"Cyprus" int4 NULL,
	"Bulgaria" int4 NULL,
	"Netherlands" int4 NULL,
	"Latvia" int4 NULL,
	"Israel" int4 NULL,
	"Belarus" int4 NULL,
	"Germany" int4 NULL,
	"Russia" int4 NULL,
	"Norway" int4 NULL,
	"Australia" int4 NULL,
	"Belgium" int4 NULL,
	"United Kingdom" int4 NULL,
	"Croatia" int4 NULL,
	"Greece" int4 NULL,
	"Lithuania" int4 NULL,
	"Serbia" int4 NULL,
	"Macedonia" int4 NULL,
	"Albania" int4 NULL,
	"Estonia" int4 NULL,
	"Ukraine" int4 NULL,
	"Italy" int4 NULL,
	"Poland" int4 NULL,
	"Slovenia" int4 NULL,
	"Hungary" int4 NULL,
	"Montenegro" int4 NULL,
	"Sweden" int4 NULL,
	"year" int4 NULL
);


CREATE TABLE public."2021_poll_results" (
	"Contestant" varchar(50) NULL,
	my_eurovision_scoreboard_points int4 NULL,
	eurovision_world_points int4 NULL,
	eurojury_jury_points int4 NULL,
	eurojury_online_points int4 NULL,
	discord_points int4 NULL,
	wiwiblogs_points int4 NULL,
	ogae_points int4 NULL,
	"year" int4 NULL
);



CREATE TABLE public."2021_televote_results" (
	"Contestant" varchar(50) NULL,
	"Total score" int4 NULL,
	"Jury score" int4 NULL,
	"Televoting score" int4 NULL,
	"Austria" int4 NULL,
	"Iceland" int4 NULL,
	"Azerbaijan" int4 NULL,
	"San Marino" int4 NULL,
	"Czech Republic" int4 NULL,
	"Ireland" int4 NULL,
	"Georgia" int4 NULL,
	"Bosnia and Herzegovina" int4 NULL,
	"Malta" int4 NULL,
	"Spain" int4 NULL,
	"Finland" int4 NULL,
	"Switzerland" int4 NULL,
	"Denmark" int4 NULL,
	"France" int4 NULL,
	"Moldova" int4 NULL,
	"Armenia" int4 NULL,
	"Cyprus" int4 NULL,
	"Bulgaria" int4 NULL,
	"Netherlands" int4 NULL,
	"Latvia" int4 NULL,
	"Israel" int4 NULL,
	"Belarus" int4 NULL,
	"Germany" int4 NULL,
	"Russia" int4 NULL,
	"Norway" int4 NULL,
	"Australia" int4 NULL,
	"Belgium" int4 NULL,
	"United Kingdom" int4 NULL,
	"Croatia" int4 NULL,
	"Greece" int4 NULL,
	"Lithuania" int4 NULL,
	"Serbia" int4 NULL,
	"Macedonia" int4 NULL,
	"Albania" int4 NULL,
	"Estonia" int4 NULL,
	"Ukraine" int4 NULL,
	"Italy" int4 NULL,
	"Poland" int4 NULL,
	"Slovenia" int4 NULL,
	"Hungary" int4 NULL,
	"Montenegro" int4 NULL,
	"Sweden" int4 NULL,
	"year" int4 NULL
);

-- 2022 
CREATE TABLE public."2022_jury_results" (
	"Contestant" varchar(50) NULL,
	"Total score" int4 NULL,
	"Jury score" int4 NULL,
	"Televoting score" int4 NULL,
	"Austria" int4 NULL,
	"Iceland" int4 NULL,
	"Azerbaijan" int4 NULL,
	"San Marino" int4 NULL,
	"Czech Republic" int4 NULL,
	"Ireland" int4 NULL,
	"Georgia" int4 NULL,
	"Bosnia and Herzegovina" int4 NULL,
	"Malta" int4 NULL,
	"Spain" int4 NULL,
	"Finland" int4 NULL,
	"Switzerland" int4 NULL,
	"Denmark" int4 NULL,
	"France" int4 NULL,
	"Moldova" int4 NULL,
	"Armenia" int4 NULL,
	"Cyprus" int4 NULL,
	"Bulgaria" int4 NULL,
	"Netherlands" int4 NULL,
	"Latvia" int4 NULL,
	"Israel" int4 NULL,
	"Belarus" int4 NULL,
	"Germany" int4 NULL,
	"Russia" int4 NULL,
	"Norway" int4 NULL,
	"Australia" int4 NULL,
	"Belgium" int4 NULL,
	"United Kingdom" int4 NULL,
	"Croatia" int4 NULL,
	"Greece" int4 NULL,
	"Lithuania" int4 NULL,
	"Serbia" int4 NULL,
	"Macedonia" int4 NULL,
	"Albania" int4 NULL,
	"Estonia" int4 NULL,
	"Ukraine" int4 NULL,
	"Italy" int4 NULL,
	"Poland" int4 NULL,
	"Slovenia" int4 NULL,
	"Hungary" int4 NULL,
	"Montenegro" int4 NULL,
	"Sweden" int4 NULL,
	"year" int4 NULL
);


CREATE TABLE public."2022_poll_results" (
	"Contestant" varchar(50) NULL,
	my_eurovision_scoreboard_points int4 NULL,
	eurovision_world_points int4 NULL,
	eurojury_jury_points int4 NULL,
	eurojury_online_points int4 NULL,
	discord_points int4 NULL,
	wiwiblogs_points int4 NULL,
	ogae_points int4 NULL,
	"year" int4 NULL
);



CREATE TABLE public."2022_televote_results" (
	"Contestant" varchar(50) NULL,
	"Total score" int4 NULL,
	"Jury score" int4 NULL,
	"Televoting score" int4 NULL,
	"Austria" int4 NULL,
	"Iceland" int4 NULL,
	"Azerbaijan" int4 NULL,
	"San Marino" int4 NULL,
	"Czech Republic" int4 NULL,
	"Ireland" int4 NULL,
	"Georgia" int4 NULL,
	"Bosnia and Herzegovina" int4 NULL,
	"Malta" int4 NULL,
	"Spain" int4 NULL,
	"Finland" int4 NULL,
	"Switzerland" int4 NULL,
	"Denmark" int4 NULL,
	"France" int4 NULL,
	"Moldova" int4 NULL,
	"Armenia" int4 NULL,
	"Cyprus" int4 NULL,
	"Bulgaria" int4 NULL,
	"Netherlands" int4 NULL,
	"Latvia" int4 NULL,
	"Israel" int4 NULL,
	"Belarus" int4 NULL,
	"Germany" int4 NULL,
	"Russia" int4 NULL,
	"Norway" int4 NULL,
	"Australia" int4 NULL,
	"Belgium" int4 NULL,
	"United Kingdom" int4 NULL,
	"Croatia" int4 NULL,
	"Greece" int4 NULL,
	"Lithuania" int4 NULL,
	"Serbia" int4 NULL,
	"Macedonia" int4 NULL,
	"Albania" int4 NULL,
	"Estonia" int4 NULL,
	"Ukraine" int4 NULL,
	"Italy" int4 NULL,
	"Poland" int4 NULL,
	"Slovenia" int4 NULL,
	"Hungary" int4 NULL,
	"Montenegro" int4 NULL,
	"Sweden" int4 NULL,
	"year" int4 NULL
);


-- 2023
CREATE TABLE public."2023_jury_results" (
	"Contestant" varchar(50) NULL,
	"Total score" int4 NULL,
	"Jury score" int4 NULL,
	"Televoting score" int4 NULL,
	"Austria" int4 NULL,
	"Iceland" int4 NULL,
	"Azerbaijan" int4 NULL,
	"San Marino" int4 NULL,
	"Czech Republic" int4 NULL,
	"Ireland" int4 NULL,
	"Georgia" int4 NULL,
	"Bosnia and Herzegovina" int4 NULL,
	"Malta" int4 NULL,
	"Spain" int4 NULL,
	"Finland" int4 NULL,
	"Switzerland" int4 NULL,
	"Denmark" int4 NULL,
	"France" int4 NULL,
	"Moldova" int4 NULL,
	"Armenia" int4 NULL,
	"Cyprus" int4 NULL,
	"Bulgaria" int4 NULL,
	"Netherlands" int4 NULL,
	"Latvia" int4 NULL,
	"Israel" int4 NULL,
	"Belarus" int4 NULL,
	"Germany" int4 NULL,
	"Russia" int4 NULL,
	"Norway" int4 NULL,
	"Australia" int4 NULL,
	"Belgium" int4 NULL,
	"United Kingdom" int4 NULL,
	"Croatia" int4 NULL,
	"Greece" int4 NULL,
	"Lithuania" int4 NULL,
	"Serbia" int4 NULL,
	"Macedonia" int4 NULL,
	"Albania" int4 NULL,
	"Estonia" int4 NULL,
	"Ukraine" int4 NULL,
	"Italy" int4 NULL,
	"Poland" int4 NULL,
	"Slovenia" int4 NULL,
	"Hungary" int4 NULL,
	"Montenegro" int4 NULL,
	"Sweden" int4 NULL,
	"year" int4 NULL
);


CREATE TABLE public."2023_poll_results" (
	"Contestant" varchar(50) NULL,
	my_eurovision_scoreboard_points int4 NULL,
	eurovision_world_points int4 NULL,
	eurojury_jury_points int4 NULL,
	eurojury_online_points int4 NULL,
	discord_points int4 NULL,
	wiwiblogs_points int4 NULL,
	ogae_points int4 NULL,
	"year" int4 NULL
);



CREATE TABLE public."2023_televote_results" (
	"Contestant" varchar(50) NULL,
	"Total score" int4 NULL,
	"Jury score" int4 NULL,
	"Televoting score" int4 NULL,
	"Austria" int4 NULL,
	"Iceland" int4 NULL,
	"Azerbaijan" int4 NULL,
	"San Marino" int4 NULL,
	"Czech Republic" int4 NULL,
	"Ireland" int4 NULL,
	"Georgia" int4 NULL,
	"Bosnia and Herzegovina" int4 NULL,
	"Malta" int4 NULL,
	"Spain" int4 NULL,
	"Finland" int4 NULL,
	"Switzerland" int4 NULL,
	"Denmark" int4 NULL,
	"France" int4 NULL,
	"Moldova" int4 NULL,
	"Armenia" int4 NULL,
	"Cyprus" int4 NULL,
	"Bulgaria" int4 NULL,
	"Netherlands" int4 NULL,
	"Latvia" int4 NULL,
	"Israel" int4 NULL,
	"Belarus" int4 NULL,
	"Germany" int4 NULL,
	"Russia" int4 NULL,
	"Norway" int4 NULL,
	"Australia" int4 NULL,
	"Belgium" int4 NULL,
	"United Kingdom" int4 NULL,
	"Croatia" int4 NULL,
	"Greece" int4 NULL,
	"Lithuania" int4 NULL,
	"Serbia" int4 NULL,
	"Macedonia" int4 NULL,
	"Albania" int4 NULL,
	"Estonia" int4 NULL,
	"Ukraine" int4 NULL,
	"Italy" int4 NULL,
	"Poland" int4 NULL,
	"Slovenia" int4 NULL,
	"Hungary" int4 NULL,
	"Montenegro" int4 NULL,
	"Sweden" int4 NULL,
	"year" int4 NULL
);


--Contest Data
CREATE TABLE public.contest_data (
	"year" int4 NULL,
	host varchar(50) NULL,
	"date" varchar(50) NULL,
	semi_countries int4 NULL,
	final_countries int4 NULL,
	jury_countries_voting_final int4 NULL,
	televote_countries_voting_final int4 NULL
);



-- Country Data
CREATE TABLE public.country_data (
	country varchar(50) NULL,
	region varchar(50) NULL
);

-- Song Data
CREATE TABLE public.song_data (
	"year" int4 NULL,
	semi_final varchar(50) NULL,
	semi_draw_position varchar(50) NULL,
	final_draw_position varchar(50) NULL,
	country varchar(50) NULL,
	artist_name varchar(50) NULL,
	song_name varchar(50) NULL,
	"language" varchar(50) NULL,
	"style" varchar(50) NULL,
	direct_qualifier_10 varchar(50) NULL,
	gender varchar(50) NULL,
	main_singers int4 NULL,
	age varchar(50) NULL,
	selection varchar(50) NULL,
	"key" varchar(50) NULL,
	"BPM" varchar(50) NULL,
	energy varchar(50) NULL,
	danceability varchar(50) NULL,
	happiness varchar(50) NULL,
	loudness varchar(50) NULL,
	acousticness varchar(50) NULL,
	instrumentalness varchar(50) NULL,
	liveness varchar(50) NULL,
	speechiness varchar(50) NULL,
	release_date varchar(50) NULL,
	key_change_10 varchar(50) NULL,
	backing_dancers varchar(50) NULL,
	backing_singers varchar(50) NULL,
	backing_instruments varchar(50) NULL,
	instrument_10 int4 NULL,
	qualified_10 varchar(50) NULL,
	final_televote_points int4 NULL,
	final_jury_points int4 NULL,
	final_televote_votes int4 NULL,
	final_jury_votes int4 NULL,
	final_place int4 NULL,
	final_total_points int4 NULL,
	semi_place int4 NULL,
	semi_televote_points int4 NULL,
	semi_jury_points int4 NULL,
	semi_total_points int4 NULL,
	favourite_10 int4 NULL,
	race varchar(50) NULL,
	host_10 int4 NULL
);